INSERT INTO "user" (first_name, last_name, username, password, is_active)
VALUES ('Ginevra', 'Granger', 'Ginevra', 'Password130', TRUE),
       ('Theodore', 'Nott', 'Theodore', 'Password131', TRUE),
       ('Daphne', 'Greengrass', 'Daphne', 'Password132', TRUE),
       ('Pansy', 'Parkinson', 'Pansy', 'Password133', TRUE),
       ('Tracey', 'Davis', 'Tracey', 'Password134', TRUE),
       ('Millicent', 'Bulstrode', 'Millicent', 'Password135', TRUE),
       ('Gregory', 'Goyle', 'Gregory', 'Password136', TRUE),
       ('Vincent', 'Crabbe', 'Vincent', 'Password137', TRUE),
       ('Padma', 'Patil', 'Padma', 'Password138', TRUE),
       ('Parvati', 'Patil', 'Parvati', 'Password139', TRUE),
       ('Harry', 'Potter', 'Potter', 'Password123', TRUE),
       ('Hermione', 'Granger', 'Hermione', 'Password456', TRUE),
       ('Ron', 'Weasley', 'Ron', 'Password789', TRUE),
       ('Luna', 'Lovegood', 'Luna', 'Password115', TRUE),
       ('Ginny', 'Weasley', 'Ginny', 'Password116', TRUE),

       ('Albus', 'Dumbledore', 'Dumbledore', 'Password101', TRUE),
       ('Severus', 'Snape', 'Severus', 'Password111', TRUE),
       ('Minerva', 'McGonagall', 'Minerva', 'Password112', TRUE),
       ('Rubeus', 'Hagrid', 'Hagrid', 'Password113', TRUE),
       ('Sybill', 'Trelawney', 'Trelawney', 'Password114', FALSE),
       ('Sirius', 'Black', 'Black', 'Password119', TRUE),
       ('Argus', 'Filch', 'Argus', 'Password120', TRUE),
       ('Filius', 'Flitwick', 'Filius', 'Password121', TRUE),
       ('Gilderoy', 'Lockhart', 'Lockhart', 'Password122', TRUE),
       ('Poppy', 'Pomfrey', 'Pomfrey', 'Password123', TRUE),
       ('Horace', 'Slughorn', 'Slughorn', 'Password125', TRUE),
       ('Godric', 'Gryffindor', 'Gryffindor', 'Password126', TRUE),
       ('Helga', 'Hufflepuff', 'Hufflepuff', 'Password127', TRUE),
       ('Rowena', 'Ravenclaw', 'Ravenclaw', 'Password128', TRUE),
       ('Salazar', 'Slytherin', 'Slytherin', 'Password129', TRUE);


INSERT INTO "training_type" (training_type_name)
VALUES ('CARDIO'),
       ('STRENGTH'),
       ('FLEXIBILITY'),
       ('BALANCE'),
       ('COORDINATION'),
       ('CARE'),
       ('POTIONS'),
       ('DEFENSE'),
       ('HERBOLOGY'),
       ('DIVINATION'),
       ('TRANSFIGURATION');


INSERT INTO "trainer" (specialization_id, user_id)
VALUES ((SELECT id FROM "training_type" WHERE training_type_name = 'DEFENSE'),
        (SELECT id FROM "user" WHERE username = 'Black')),
       ((SELECT id FROM "training_type" WHERE training_type_name = 'POTIONS'),
        (SELECT id FROM "user" WHERE username = 'Severus')),
       ((SELECT id FROM "training_type" WHERE training_type_name = 'CARE'),
        (SELECT id FROM "user" WHERE username = 'Hagrid')),
       ((SELECT id FROM "training_type" WHERE training_type_name = 'TRANSFIGURATION'),
        (SELECT id FROM "user" WHERE username = 'Minerva')),
       ((SELECT id FROM "training_type" WHERE training_type_name = 'DIVINATION'),
        (SELECT id FROM "user" WHERE username = 'Dumbledore')),
       ((SELECT id FROM training_type WHERE training_type_name = 'CARDIO'),
        (SELECT id FROM "user" WHERE username = 'Argus')),
       ((SELECT id FROM training_type WHERE training_type_name = 'STRENGTH'),
        (SELECT id FROM "user" WHERE username = 'Filius')),
       ((SELECT id FROM training_type WHERE training_type_name = 'FLEXIBILITY'),
        (SELECT id FROM "user" WHERE username = 'Lockhart')),
       ((SELECT id FROM training_type WHERE training_type_name = 'POTIONS'),
        (SELECT id FROM "user" WHERE username = 'Gryffindor')),
       ((SELECT id FROM training_type WHERE training_type_name = 'BALANCE'),
        (SELECT id FROM "user" WHERE username = 'Pomfrey')),
       ((SELECT id FROM training_type WHERE training_type_name = 'COORDINATION'),
        (SELECT id FROM "user" WHERE username = 'Slughorn')),
       ((SELECT id FROM training_type WHERE training_type_name = 'DEFENSE'),
        (SELECT id FROM "user" WHERE username = 'Hufflepuff')),
       ((SELECT id FROM training_type WHERE training_type_name = 'HERBOLOGY'),
        (SELECT id FROM "user" WHERE username = 'Ravenclaw')),
       ((SELECT id FROM training_type WHERE training_type_name = 'DIVINATION'),
        (SELECT id FROM "user" WHERE username = 'Slytherin'));


INSERT INTO trainee (date_of_birth, address, user_id)
VALUES ('1980-07-31', '4 Privet Drive, Little Whinging', (SELECT id FROM "user" WHERE username = 'Potter')),
       ('1979-09-19', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Hermione')),
       ('1980-03-01', 'The Burrow, Ottery St Catchpole', (SELECT id FROM "user" WHERE username = 'Ron')),
       ('1981-02-13', 'The Lovegood House', (SELECT id FROM "user" WHERE username = 'Luna')),
       ('1981-08-11', 'The Burrow, Ottery St Catchpole', (SELECT id FROM "user" WHERE username = 'Ginny')),
       ('1981-09-01', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Ginevra')),
       ('1980-06-06', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Theodore')),
       ('1982-07-07', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Daphne')),
       ('1982-12-12', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Pansy')),
       ('1981-11-11', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Tracey')),
       ('1982-05-05', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Millicent')),
       ('1980-10-10', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Gregory')),
       ('1981-08-08', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Vincent')),
       ('1982-04-04', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Padma')),
       ('1982-01-01', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Parvati')),
       ('1981-08-11', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Ginevra')),
       ('1979-09-13', 'Nott Manor, England', (SELECT id FROM "user" WHERE username = 'Theodore')),
       ('1980-04-29', 'Greengrass Manor, England', (SELECT id FROM "user" WHERE username = 'Daphne')),
       ('1980-10-28', 'Parkinson Manor, England', (SELECT id FROM "user" WHERE username = 'Pansy')),
       ('1980-05-12', 'Davis House, England', (SELECT id FROM "user" WHERE username = 'Tracey')),
       ('1979-07-19', 'Bulstrode House, England', (SELECT id FROM "user" WHERE username = 'Millicent')),
       ('1980-01-14', 'Goyle House, England', (SELECT id FROM "user" WHERE username = 'Gregory')),
       ('1980-03-11', 'Crabbe House, England', (SELECT id FROM "user" WHERE username = 'Vincent')),
       ('1979-11-22', 'Patil House, England', (SELECT id FROM "user" WHERE username = 'Padma')),
       ('1979-11-22', 'Patil House, England', (SELECT id FROM "user" WHERE username = 'Parvati')),
       ('1980-07-31', '4 Privet Drive, Little Whinging', (SELECT id FROM "user" WHERE username = 'Potter')),
       ('1979-09-19', 'Hogwarts, Scotland', (SELECT id FROM "user" WHERE username = 'Hermione')),
       ('1980-03-01', 'The Burrow, Ottery St Catchpole', (SELECT id FROM "user" WHERE username = 'Ron')),
       ('1981-02-13', 'The Lovegood House, England', (SELECT id FROM "user" WHERE username = 'Luna')),
       ('1981-08-11', 'The Burrow, Ottery St Catchpole', (SELECT id FROM "user" WHERE username = 'Ginny'));
