DROP TABLE IF EXISTS "roles" CASCADE;
DROP TABLE IF EXISTS "role_authorities" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
DROP TABLE IF EXISTS "tokens" CASCADE;
DROP TABLE IF EXISTS "trainer" CASCADE;
DROP TABLE IF EXISTS "trainee" CASCADE;
DROP TABLE IF EXISTS "trainee_trainer" CASCADE;
DROP TABLE IF EXISTS "trainer_training_type" CASCADE;
DROP TABLE IF EXISTS "training" CASCADE;
DROP TABLE IF EXISTS "training_type" CASCADE;
DROP TABLE IF EXISTS "sessions" CASCADE;
DROP TABLE IF EXISTS "training_session" CASCADE;

CREATE TABLE "roles"
(
    id         SERIAL PRIMARY KEY,
    permission VARCHAR(255) NOT NULL
);

CREATE TABLE "role_authorities"
(
    role_id   BIGINT       NOT NULL,
    authority VARCHAR(255) NOT NULL,
    FOREIGN KEY (role_id) REFERENCES "roles" (id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    is_active  BOOLEAN DEFAULT FALSE,
    permission VARCHAR(255)
);

CREATE TABLE tokens
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_type       VARCHAR(255) NOT NULL,
    access_token     VARCHAR(255) NOT NULL UNIQUE,
    access_token_ttl BIGINT,
    revoked          BOOLEAN      NOT NULL DEFAULT FALSE,
    expired          BOOLEAN      NOT NULL DEFAULT FALSE,
    user_id          BIGINT,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE SET NULL
);

CREATE TABLE training_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_type_name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE trainer
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT UNIQUE NOT NULL,
    training_type_id BIGINT        NOT NULL,

    CONSTRAINT fk_user_id
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE CASCADE,

    CONSTRAINT fk_training_type_id
        FOREIGN KEY (training_type_id)
            REFERENCES training_type (id)
            ON DELETE CASCADE
);


CREATE TABLE trainee
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_of_birth DATE,
    address       VARCHAR(255),
    user_id       BIGINT UNIQUE,
    CONSTRAINT fk_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
            ON DELETE SET NULL
);

CREATE TABLE trainee_trainer
(
    trainee_id BIGINT NOT NULL,
    trainer_id BIGINT NOT NULL,
    CONSTRAINT fk_trainee
        FOREIGN KEY (trainee_id)
            REFERENCES trainee (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_trainer
        FOREIGN KEY (trainer_id)
            REFERENCES trainer (id)
            ON DELETE CASCADE,
    PRIMARY KEY (trainee_id, trainer_id)
);

CREATE TABLE training
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainee_id        BIGINT       NOT NULL,
    trainer_id        BIGINT       NOT NULL,
    training_name     VARCHAR(255) NOT NULL,
    training_type_id  BIGINT       NOT NULL,
    training_date     DATE         NOT NULL,
    training_duration INT          NOT NULL,
    CONSTRAINT fk_trainee
        FOREIGN KEY (trainee_id)
            REFERENCES trainee (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_trainer
        FOREIGN KEY (trainer_id)
            REFERENCES trainer (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_training_type
        FOREIGN KEY (training_type_id)
            REFERENCES training_type (id)
            ON DELETE CASCADE
);

CREATE TABLE trainer_training_type
(
    trainer_id       BIGINT,
    training_type_id BIGINT,
    PRIMARY KEY (trainer_id, training_type_id),
    CONSTRAINT fk_trainer
        FOREIGN KEY (trainer_id)
            REFERENCES trainer (id)
            ON DELETE CASCADE,
    CONSTRAINT fk_training_type
        FOREIGN KEY (training_type_id)
            REFERENCES training_type (id)
            ON DELETE CASCADE
);

CREATE TABLE training_session
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_id         BIGINT    NOT NULL,
    session_start       TIMESTAMP NOT NULL,
    session_end         TIMESTAMP NOT NULL,
    session_description TEXT,
    CONSTRAINT fk_training
        FOREIGN KEY (training_id)
            REFERENCES training (id)
            ON DELETE CASCADE
);

CREATE TABLE sessions
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_id  BIGINT,
    training_id BIGINT,
    start_time  TIMESTAMP,
    end_time    TIMESTAMP,
    CONSTRAINT fk_trainer
        FOREIGN KEY (trainer_id)
            REFERENCES trainer (id)
            ON DELETE SET NULL,
    CONSTRAINT fk_training
        FOREIGN KEY (training_id)
            REFERENCES training (id)
            ON DELETE CASCADE
);

SELECT count(*)
from trainer;

SELECT *
FROM workload w
         JOIN year_summary ys ON w.id = ys.workload_id
         JOIN month_summary ms ON ys.id = ms.year_summary_id
WHERE w.trainer_name = 'Theodore.Nott';


-- SELECT w.id, w.username, w.first_name, w.last_name, w.active,
--        w.training_date, w.duration, w.action_type
-- FROM trainerWorkload w
--          JOIN year_summary ys ON w.id = ys.workload_id
--          JOIN month_summary ms ON ys.id = ms.year_summary_id
-- WHERE w.username = 'Theodore.Nott'
--   AND w.training_date BETWEEN '2023-01-01' AND '2024-01-31';
