DROP TABLE IF EXISTS "workload" CASCADE;
DROP TABLE IF EXISTS "training_workload" CASCADE;
DROP TABLE IF EXISTS "year_summary" CASCADE;
DROP TABLE IF EXISTS "month_summary" CASCADE;

CREATE TABLE workload
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trainer_name VARCHAR(255) NOT NULL,
    active       BOOLEAN      NOT NULL,
    action_type  VARCHAR(255) NOT NULL
);

CREATE TABLE training_workload
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    training_name     VARCHAR(255) NOT NULL,
    training_type     VARCHAR(255) NOT NULL,
    training_duration BIGINT       NOT NULL,
    training_date     DATE         NOT NULL,
    trainer_id        BIGINT       NOT NULL,
    CONSTRAINT fk_trainer_workload FOREIGN KEY (trainer_id) REFERENCES workload (id) ON DELETE CASCADE
);

CREATE TABLE year_summary
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year        INT    NOT NULL,
    workload_id BIGINT NOT NULL,
    CONSTRAINT fk_year_workload FOREIGN KEY (workload_id) REFERENCES workload (id) ON DELETE CASCADE
);

CREATE TABLE month_summary
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_name      VARCHAR(255) NOT NULL,
    total_duration  BIGINT       NOT NULL,
    year_summary_id BIGINT       NOT NULL,
    CONSTRAINT fk_month_year_summary FOREIGN KEY (year_summary_id) REFERENCES year_summary (id) ON DELETE CASCADE
);
