server:
  port: 8090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://oregon-postgres.render.com:5432/gym_user
    username: admin_gym_user
    password: tuZdX3joSSGMZ8RESK5ZhognKKwH9kbN
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jms:
    pub-sub-domain: true
    jms-template:
      default-destination: trainer.summary.queue
  json:
    trusted:
      packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
  health:
    circuitbreakers:
      enabled: true
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      userService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

  retry:
    instances:
      userService:
        maxRetryAttempts: 5
        waitDuration: 10s

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

jwt:
  secret: secret
  issuer: myIssuer
  access: 36000000
  refresh: 72000000
  expiration: 36000000

