server:
  port: 8060
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://oregon-postgres.render.com:5432/gym_user
    username: admin_gym_user
    password: tuZdX3joSSGMZ8RESK5ZhognKKwH9kbN
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jms:
    pub-sub-domain: true
    jms-template:
      default-destination: trainer.summary.queue
  json:
    trusted:
      packages: "*"

application:
  config:
    user-url: http://localhost:8222/api/users
    trainee-url: http://localhost:8222/api/trainees
    trainer-url: http://localhost:8222/api/trainers
    training-url: http://localhost:8222/api/trainings

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    info:
      enabled: true
